name: guardian_info_app
description: "A new Flutter project for Guardian Info App."

# Prevent accidental publication to pub.dev
publish_to: 'none'

# Application version
version: 1.0.0+1

# Flutter SDK environment
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies required for the project
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Adding image assets
  assets:
    - assets/images/
    # Add more assets here if needed, such as:
    # - assets/images/another_image.png
